spring.application.name=microservice-studies

# Configurações de conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-soft-dew-acwub35i.sa-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Z1QxbrWz8InV

# Driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto do Banco de dados
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect

# Outras configurações 
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.sql.init.platform=postgresql

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.open-in-view=false

# JWT
jwt_secret=fsdfs#5345ggd*465sdf*gs*df
jwt_expires=3600

# Credenciais do AWS Cognito
aws.cognito.url=https://cognito-idp.sa-east-1.amazonaws.com
aws.cognito.userPoolId=sa-east-1_p1oeV2px5
aws.cognito.clientId=4a9t2v0o7thl21ejjr0nahbvoa
aws.cognito.clientSecret=1iff5fvvr1fiuilvqunmchhqnoqhvc66no639jrcseiaqc248s6r

# Dizendo ao Spring Security onde fica o provedor do JWT (Issuer URI)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.sa-east-1.amazonaws.com/sa-east-1_p1oeV2px5